### PR TITLE
fix: Change deprecated testnet

### PR DESCRIPTION
**Pull request by kim201212**

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by StephenFluin** [comment]
@kim201212 we'd love to accept this contribution, but it looks like you didn't give us edit rights to the PR so we can rebase it and merge it. Can you grant those rights? 

image
image

**Comment by kim201212** [comment]
@StephenFluin I can't find anything to enable that option, can you help?

**Comment by StephenFluin** [comment]
I'd love to get this fixed. Can you grab a slot and we just spend 5 minutes
either fixing the permissions or resubmitting so I we can get it merged?
https://calendly.com/interchain-stephen/30min Sorry for these difficulties.
Hopefully by seeing what you're running into we can make this better for
others in the future too.

**Comment by StephenFluin** [comment]
We tested this, just check the box at the bottom of the right column (per the picture) and we get future PRs rebased and merged much faster. We'll manually do this one in another PR this time. Thanks for the contribution!

**Pull request closed without merging**
