### PR TITLE
Centrifuge documentation

### PR DESCRIPTION
**Pull request by mustermeiszer**
Documentation for how to run a Centrifuge / Algol (testnetwork) full-node.

### CODE REVIEW

**Comment by StephenFluin** [comment]
@mustermeiszer is this PR ready for review? It is still marked as `draft`.

**Comment by mustermeiszer** [comment]
@StephenFluin It still is missing the parts to set up a `systemd`-file for a containerized setup. But the rest is good. Probably will mark as ready tomorrow or monday.

**Comment by StephenFluin** [comment]
Sounds good!

**Comment by mustermeiszer** [comment]
@StephenFluin its ready for reveiw

**Review by StephenFluin — APPROVED** [review]

**Comment by StephenFluin** [comment]
@mustermeiszer You should also edit `Navigation.astro` and add a link. (this file will be refactored to JS/TS soon, but we'll do the rework if you get a PR in.

**Pull request merged**
