### PR TITLE
feat: Cookbook Onboard (AI Assistant) integration

### PR DESCRIPTION
**Pull request by ClockRide**
## Preview
Preview link: https://axelar-docs-cookbook.vercel.app

## Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Axelar resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Axelar, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Axelar-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

image

### CODE REVIEW

**Review by ffe9f8 — APPROVED** [review]

**Comment by ffe9f8** [comment]
Hey @ClockRide, thanks for contributing to our docs! These changes look great, and I've approved them. Can you rebase so that we can merge them in?

**Comment by ClockRide** [comment]
> Hey @ClockRide, thanks for contributing to our docs! These changes look great, and I've approved them. Can you rebase so that we can merge them in?

Awesome, excited to get it merged! Just rebased the branch :)

**Review by ffe9f8 — APPROVED** [review]

**Comment by ffe9f8** [comment]
@ClockRide There were a few more updates to the repo so you should rebase again. Just approved and enabled auto-merge so it should go through as soon as that happens. Thanks for your contribution!

**Comment by ClockRide** [comment]
@ffe9f8 could you please approve deploy to Vercel so checks will pass? :)

**Comment by StephenFluin** [comment]
We can't merge this PR at this time as we're going to be unifying our chatbox experiences with axelar.network. Thank you so much for this contribution!

**Pull request closed without merging**
