### PR TITLE
feat: its sequence diagram

### PR DESCRIPTION
**Pull request by benjamin852**

### CODE REVIEW

**Review by StephenFluin — CHANGES_REQUESTED** [review]
I love the drawings but I think we should talk more about this. When I view the site the colors are all over the place (look very weird) and the text actually looks blurry. Let's figure out how to better integrate this into the site.

**Comment by StephenFluin** [comment]
I also think these diagrams need more context/explanation.

Here's what it looks like for me:
image

**Comment by StephenFluin** [comment]
@benjamin852 what's the next step on this one? Are you blocked or do you need help?

**Comment by benjamin852** [comment]
@StephenFluin made some updates here feel free to review it out now

**Pull request merged**
