### PR TITLE
fix: change links to orange

### PR DESCRIPTION
**Pull request by ffe9f8**
- Also change title back to light green

Preview (example page, make sure you're on dark mode): https://axelar-docs-git-marty-orange-links-axelar-network.vercel.app/resources/ibc-chain-onboarding

### CODE REVIEW

**Comment by galenmoore** [comment]
Orange links look good - but in combo with the green titles it's a little busy with colors imho. We might want to go back to standard white for the titles.

**Comment by ffe9f8** [comment]
> Orange links look good - but in combo with the green titles it's a little busy with colors imho. We might want to go back to standard white for the titles.

I agree. Will defer to you @galenmoore but I think white titles are better

**Comment by milapsheth** [comment]
> > Orange links look good - but in combo with the green titles it's a little busy with colors imho. We might want to go back to standard white for the titles.
> 
> I agree. Will defer to you @galenmoore but I think white titles are better

Yep, can you change it back to white?

**Comment by ffe9f8** [comment]
> > > Orange links look good - but in combo with the green titles it's a little busy with colors imho. We might want to go back to standard white for the titles.
> > 
> > 
> > I agree. Will defer to you @galenmoore but I think white titles are better
> 
> Yep, can you change it back to white?

It should still be white headings / green links in prod, will just close this PR.

**Pull request closed without merging**
